# -*- coding: utf-8 -*-
"""TASK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10q-iaKTYCQ8bgzwuAKP7rYe3YUCOZX3s
"""

import pandas as pd
import numpy as np

df = pd.read_excel("/content/Entertainment questionnaire (1) (1).xlsx")

df

df1 = df
df1
df1.columns

df1.columns = df1.iloc[0]
df1 = df1.iloc[1:].reset_index(drop=True)

df1

(df1['q9'] == "Null").sum()

(df1['q9'].isna()).sum()

df1.replace("Null", 0, inplace=True)

(df1['q9'] == "Null").sum()

(df1['q9'].isna()).sum()

df1['q9'].mode()

df1

df1['q1'] = df1['q1'].replace(1,"Male")
df1['q1'] = df1['q1'].replace(2,"Female")
df1

df1['q2'] = df1['q2'].replace(1, "18-24")
df1['q2'] = df1['q2'].replace(2, "25-30")
df1['q2'] = df1['q2'].replace(3, "31-45")
df1['q2'] = df1['q2'].replace(4, "46-55")
df1['q2'] = df1['q2'].replace(5, "56+")
df1

df1['q3'] = df1['q3'].replace(1, "Single")
df1['q3'] = df1['q3'].replace(2, "Married with no kids")
df1['q3'] = df1['q3'].replace(3, "Married with kids")
df1['q3'] = df1['q3'].replace(4, "Single with kids")
df1

df1['q4'] = df1['q4'].replace(1, "< 7000 SAR")
df1['q4'] = df1['q4'].replace(2, "7000-12000 SAR")
df1['q4'] = df1['q4'].replace(3, "13000-20000 SAR")
df1['q4'] = df1['q4'].replace(4, "> 20000 SAR")
df1

df1['q5'] = df1['q5'].replace(1, "North-West of Riyadh")
df1['q5'] = df1['q5'].replace(2, "North-East of Riyadh")
df1['q5'] = df1['q5'].replace(3, "South-West of Riyadh")
df1['q5'] = df1['q5'].replace(4, "South-East of Riyadh")
df1

df1['q7'] = df1['q7'].replace(1, "I only go out on weekends")
df1['q7'] = df1['q7'].replace(2, "2-3 Times a week")
df1['q7'] = df1['q7'].replace(3, "+3 Times a week")
df1

df1['q8'] = df1['q8'].replace(1, "I only attend free events")
df1['q8'] = df1['q8'].replace(2, "I will attend if the ticket priced reasonably")
df1['q8'] = df1['q8'].replace(3, "I will attend if the event is exciting enough")
df1['q8'] = df1['q8'].replace(4, "I will attend! ")
df1

df1['q9'] = df1['q9'].replace(1, "< 50 SAR")
df1['q9'] = df1['q9'].replace(2, "50-100 SAR")
df1['q9'] = df1['q9'].replace(3, "101-200 SAR")
df1['q9'] = df1['q9'].replace(4, "200+ SAR")
df1

df1['q6'] = df1['q6'].replace(1, "Extremly Satisfied")
df1['q6'] = df1['q6'].replace(2, "Satisfied")
df1['q6'] = df1['q6'].replace(3, "Neutral")
df1['q6'] = df1['q6'].replace(4, "Un-satisfied")
df1['q6'] = df1['q6'].replace(5, "Extremly Un-satisfied")
df1

df1 = df1.rename(columns={'q1': 'Gender', 'q2' : 'Age Group', 'q3' : 'Martial Status', 'q4' : 'Monthly Income Level', 'q5' : 'Residential Area', 'q6' : 'Satisfaction', 'q7':'Number of Going Out per week', 'q8' : 'Willing to pay', 'q9': 'How much are you willing to pay'})
df1

print(df1['Gender'].describe())
print(df1['Age Group'].describe())
print(df1['Martial Status'].describe())
print(df1['Monthly Income Level'].describe())
print(df1['Residential Area'].describe())
print(df1['Satisfaction'].describe())
print(df1['Number of Going Out per week'].describe())
print(df1['Willing to pay'].describe())
print(df1['How much are you willing to pay'].describe())

df1.to_csv('TaskDF.csv', index=False)

import pandas as pd

df = pd.read_csv("TaskDF.csv")

def assign_coordinates(area):
    if "North-West" in area:
        return 24.8300, 46.5500
    elif "North-East" in area:
        return 24.8500, 46.7700
    elif "South-West" in area:
        return 24.5800, 46.5500
    elif "South-East" in area:
        return 24.6000, 46.8000
    else:
        return None, None

df["Latitude"], df["Longitude"] = zip(*df["Residential Area"].apply(assign_coordinates))
print(df)
df.to_csv("updated_dataset.csv", index=False)

data = {
    "Age Group": ["18-24", "25-30", "31-45", "46-55", "56+",
                 "25-30", "46-55", "18-24", "56+", "31-45",
                 "31-45", "18-24", "25-30", "46-55", "56+",
                 "18-24", "31-45", "56+", "46-55", "25-30",
                 "46-55", "25-30", "18-24", "56+", "31-45"],
    "Price Category": ["0", "0", "0", "0", "0",
                       "< 50 SAR", "< 50 SAR", "< 50 SAR", "< 50 SAR", "< 50 SAR",
                       "50-100 SAR", "50-100 SAR", "50-100 SAR", "50-100 SAR", "50-100 SAR",
                       "101-200 SAR", "101-200 SAR", "101-200 SAR", "101-200 SAR", "101-200 SAR",
                       "200+ SAR", "200+ SAR", "200+ SAR", "200+ SAR", "200+ SAR"],
    "Count": [41, 47, 34, 49, 52,
              5, 7, 10, 11, 16,
              5, 8, 8, 8, 9,
              15, 15, 16, 19, 28,
              15, 16, 19, 22, 25],
    "Price": [0, 0, 0, 0, 0,
              25, 25, 25, 25, 25,
              75, 75, 75, 75, 75,
              150, 150, 150, 150, 150,
              250, 250, 250, 250, 250],
    "Revenue": [0, 0, 0, 0, 0,
                125, 175, 250, 275, 400,
                375, 600, 600, 600, 675,
                2250, 2250, 2400, 2850, 4200,
                3750, 4000, 4750, 5500, 6250]
}
df = pd.DataFrame(data)
print(df)
df.to_csv("Age Group.csv", index=False)

data = {
    "Price Category": ["< 50 SAR", "0", "101-200 SAR", "200+ SAR", "50-100 SAR"],
    "Count": [49, 223, 93, 97, 38],
    "Price": [25, 0, 150, 250, 75],
    "Revenue": [1225, 0, 13950, 24250, 2850]
}

df = pd.DataFrame(data)
print(df)
df.to_csv("Original.csv", index=False)

data = {
    "Price Category": ["< 50 SAR", "< 50 SAR", "0", "0", "101-200 SAR", "101-200 SAR", "200+ SAR", "200+ SAR", "50-100 SAR", "50-100 SAR"],
    "Count": [49, 49, 223, 223, 93, 93, 97, 97, 38, 38],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female"],
    "Gender Count": [19, 30, 102, 121, 35, 58, 45, 52, 22, 16],
    "Price": [25, 25, 0, 0, 150, 150, 250, 250, 75, 75],
    "Revenue": [475, 750, 0, 0, 5250, 8700, 11250, 13000, 1650, 1200]
}
df = pd.DataFrame(data)
print(df)
df.to_csv("Gender.csv", index=False)

data = {
    "Price Category": ["< 50 SAR", "< 50 SAR", "< 50 SAR", "< 50 SAR", "0", "0", "0", "0",
                       "101-200 SAR", "101-200 SAR", "101-200 SAR", "101-200 SAR",
                       "200+ SAR", "200+ SAR", "200+ SAR", "200+ SAR",
                       "50-100 SAR", "50-100 SAR", "50-100 SAR", "50-100 SAR"],
    "Count": [49, 49, 49, 49, 223, 223, 223, 223,
              93, 93, 93, 93,
              97, 97, 97, 97,
              38, 38, 38, 38],
    "Area": ["South-West Riyadh", "South-East Riyadh", "North-West Riyadh", "North-East Riyadh",
             "South-West Riyadh", "South-East Riyadh", "North-West Riyadh", "North-East Riyadh",
             "South-West Riyadh", "South-East Riyadh", "North-West Riyadh", "North-East Riyadh",
             "South-West Riyadh", "South-East Riyadh", "North-West Riyadh", "North-East Riyadh",
             "South-West Riyadh", "South-East Riyadh", "North-West Riyadh", "North-East Riyadh"],
    "Area Count": [12, 14, 10, 13,
                   64, 65, 47, 47,
                   23, 13, 31, 26,
                   19, 20, 29, 29,
                   8, 14, 6, 10],
    "Price": [25, 25, 25, 25, 0, 0, 0, 0,
              150, 150, 150, 150,
              250, 250, 250, 250,
              75, 75, 75, 75],
    "Revenue": [300, 350, 250, 225,
                0, 0, 0, 0,
                3450, 1950, 4650, 3900,
                4750, 5000, 7250, 7250,
                600, 1050, 450, 780]
}
df = pd.DataFrame(data)
print(df)
df.to_csv("Residential Area.csv", index=False)

data = {
    "Age Group": ["18-24", "25-30", "31-45", "46-55", "56+",
                 "25-30", "46-55", "18-24", "56+", "31-45",
                 "31-45", "18-24", "25-30", "46-55", "56+",
                 "18-24", "31-45", "56+", "46-55", "25-30",
                 "46-55", "25-30", "18-24", "56+", "31-45"],
    "Price Category": ["0", "0", "0", "0", "0",
                       "< 50 SAR", "< 50 SAR", "< 50 SAR", "< 50 SAR", "< 50 SAR",
                       "50-100 SAR", "50-100 SAR", "50-100 SAR", "50-100 SAR", "50-100 SAR",
                       "101-200 SAR", "101-200 SAR", "101-200 SAR", "101-200 SAR", "101-200 SAR",
                       "200+ SAR", "200+ SAR", "200+ SAR", "200+ SAR", "200+ SAR"],
    "Count": [41, 47, 34, 49, 52,
              5, 7, 10, 11, 16,
              5, 8, 8, 8, 9,
              15, 15, 16, 19, 28,
              15, 16, 19, 22, 25],
    "Price": [0, 0, 0, 0, 0,
              25, 25, 25, 25, 25,
              75, 75, 75, 75, 75,
              150, 150, 150, 150, 150,
              250, 250, 250, 250, 250],
    "Revenue": [0, 0, 0, 0, 0,
                125, 175, 250, 275, 400,
                375, 600, 600, 600, 675,
                2250, 2250, 2400, 2850, 4200,
                3750, 4000, 4750, 5500, 6250]
}
df = pd.DataFrame(data)
print(df)
df.to_csv("Age Group.csv", index=False)

!pip install cplex
!pip install docplex
import cplex

import docplex
import pandas as pd
from docplex.mp.model import Model

df = pd.read_csv("TaskDF.csv")